export default [
  { id: 0, value: "Abaltzisketa" },
  { id: 1, value: "Aduna" },
  { id: 2, value: "Aizarnazabal" },
  { id: 3, value: "Albiztur" },
  { id: 4, value: "Alegia" },
  { id: 5, value: "Alkiza" },
  { id: 6, value: "Altzo" },
  { id: 7, value: "Amezketa" },
  { id: 8, value: "Andoain" },
  { id: 9, value: "Anoeta" },
  { id: 10, value: "Antzuola" },
  { id: 11, value: "Arama" },
  { id: 12, value: "Aretxabaleta" },
  { id: 13, value: "Asteasu" },
  { id: 14, value: "Ataun" },
  { id: 15, value: "Aia" },
  { id: 16, value: "Azkoitia" },
  { id: 17, value: "Azpeitia" },
  { id: 18, value: "Beasain" },
  { id: 19, value: "Beizama" },
  { id: 20, value: "Belauntza" },
  { id: 21, value: "Berastegi" },
  { id: 22, value: "Berrobi" },
  { id: 23, value: "Bidegoian/Bidania-Goiatz" },
  { id: 24, value: "Zegama" },
  { id: 25, value: "Zerain" },
  { id: 26, value: "Zestoa" },
  { id: 27, value: "Zizurkil" },
  { id: 28, value: "Deba" },
  { id: 29, value: "Eibar" },
  { id: 30, value: "Elduain" },
  { id: 31, value: "Elgoibar" },
  { id: 32, value: "Elgeta" },
  { id: 33, value: "Eskoriatza" },
  { id: 34, value: "Ezkio-Itsaso" },
  { id: 35, value: "Hondarribia" },
  { id: 36, value: "Gaintza" },
  { id: 37, value: "Gabiria" },
  { id: 38, value: "Getaria" },
  { id: 39, value: "Hernani" },
  { id: 40, value: "Hernialde" },
  { id: 41, value: "Ibarra" },
  { id: 42, value: "Idiazabal" },
  { id: 43, value: "Ikaztegieta" },
  { id: 44, value: "Irun" },
  { id: 45, value: "Irura" },
  { id: 46, value: "Itsasondo" },
  { id: 47, value: "Larraul" },
  { id: 48, value: "Lazkao" },
  { id: 49, value: "Leaburu" },
  { id: 50, value: "Legazpi" },
  { id: 51, value: "Legorreta" },
  { id: 52, value: "Lezo" },
  { id: 53, value: "Lizartza" },
  { id: 54, value: "Arrasate/Mondrag\u00f3n/Arrasate" },
  { id: 55, value: "Mutriku" },
  { id: 56, value: "Mutiloa" },
  { id: 57, value: "Olaberria" },
  { id: 58, value: "O\u00f1ati" },
  { id: 59, value: "Orexa" },
  { id: 60, value: "Orio" },
  { id: 61, value: "Ormaiztegi" },
  { id: 62, value: "Oiartzun" },
  { id: 63, value: "Pasaia" },
  { id: 64, value: "Soraluze-Placencia De Las Armas/Soraluze" },
  { id: 65, value: "Errezil" },
  { id: 66, value: "Errenteria" },
  { id: 67, value: "Leintz-Gatzaga/Leintz Gatzaga" },
  { id: 68, value: "Donostia-San Sebasti\u00e1n/Donostia" },
  { id: 69, value: "Segura" },
  { id: 70, value: "Tolosa" },
  { id: 71, value: "Urnieta" },
  { id: 72, value: "Usurbil" },
  { id: 73, value: "Bergara" },
  { id: 74, value: "Villabona/Villabona-Amasa" },
  { id: 75, value: "Ordizia" },
  { id: 76, value: "Urretxu" },
  { id: 77, value: "Zaldibia" },
  { id: 78, value: "Zarautz" },
  { id: 79, value: "Zumarraga" },
  { id: 80, value: "Zumaia" },
  { id: 81, value: "Mendaro" },
  { id: 82, value: "Lasarte-Oria" },
  { id: 83, value: "Astigarraga" },
  { id: 84, value: "Baliarrain" },
  { id: 85, value: "Orendain" },
  { id: 86, value: "Altzaga" },
  { id: 87, value: "Gaztelu" },
  { id: 88, value: "Ab\u00e1igar/Abaigar" },
  { id: 89, value: "Ab\u00e1rzuza <> Abartzuza/Abartzuza" },
  { id: 90, value: "Abaurregaina/Abaurrea Alta/Abaurregaina" },
  { id: 91, value: "Abaurrepea/Abaurrea Baja/Abaurrepea" },
  { id: 92, value: "Aberin" },
  { id: 93, value: "Ablitas" },
  { id: 94, value: "Adi\u00f3s/Adios" },
  { id: 95, value: "Aguilar De Cod\u00e9s/Aguilar Kodes" },
  { id: 96, value: "Aibar <> Oibar/Oibar" },
  { id: 97, value: "Altsasu/Alsasua/Altsasu" },
  { id: 98, value: "All\u00edn <> Allin/Allin" },
  { id: 99, value: "Allo" },
  { id: 100, value: "Am\u00e9scoa Baja/Ameskoabarrena" },
  { id: 101, value: "Anc\u00edn <> Antzin/Antzin" },
  { id: 102, value: "Andosilla" },
  { id: 103, value: "Anso\u00e1in <> Antsoain/Antsoain" },
  { id: 104, value: "Anue" },
  { id: 105, value: "A\u00f1orbe" },
  { id: 106, value: "Aoiz/Agoitz/Agoitz" },
  { id: 107, value: "Araitz" },
  { id: 108, value: "Aranarache <> Aranaratxe/Aranaratxe" },
  { id: 109, value: "Arantza" },
  { id: 110, value: "Aranguren" },
  { id: 111, value: "Arano" },
  { id: 112, value: "Arakil" },
  { id: 113, value: "Aras" },
  { id: 114, value: "Arbizu" },
  { id: 115, value: "Arce <> Artzi/Artzibar" },
  { id: 116, value: "Los Arcos" },
  { id: 117, value: "Arellano" },
  { id: 118, value: "Areso" },
  { id: 119, value: "Arguedas" },
  { id: 120, value: "Aria" },
  { id: 121, value: "Aribe" },
  { id: 122, value: "Arma\u00f1anzas/Arma\u00f1antzas" },
  { id: 123, value: "Arr\u00f3niz/Arroitz" },
  { id: 124, value: "Arruazu" },
  { id: 125, value: "Artajona/Artaxoa" },
  { id: 126, value: "Artazu" },
  { id: 127, value: "Atez/Atetz" },
  { id: 128, value: "Ayegui <> Aiegi/Aiegi" },
  { id: 129, value: "Azagra" },
  { id: 130, value: "Azuelo" },
  { id: 131, value: "Bakaiku" },
  { id: 132, value: "Bar\u00e1soain/Barasoain" },
  { id: 133, value: "Barbarin" },
  { id: 134, value: "Bargota" },
  { id: 135, value: "Barillas" },
  { id: 136, value: "Basaburua" },
  { id: 137, value: "Baztan" },
  { id: 138, value: "Beire" },
  { id: 139, value: "Belasco\u00e1in/Beraskoain" },
  { id: 140, value: "Berbinzana/Berbintzana" },
  { id: 141, value: "Bertizarana" },
  { id: 142, value: "Betelu" },
  { id: 143, value: "Biurrun-Olcoz/Biurrun-Olkotz" },
  { id: 144, value: "Bu\u00f1uel" },
  { id: 145, value: "Auritz/Burguete/Auritz" },
  { id: 146, value: "Burgui <> Burgi/Burgi" },
  { id: 147, value: "Burlada <> Burlata/Burlata" },
  { id: 148, value: "El Busto" },
  { id: 149, value: "Cabanillas" },
  { id: 150, value: "Cabredo" },
  { id: 151, value: "Cadreita" },
  { id: 152, value: "Caparroso" },
  { id: 153, value: "C\u00e1rcar" },
  { id: 154, value: "Carcastillo/Zarrakaztelu" },
  { id: 155, value: "Cascante" },
  { id: 156, value: "C\u00e1seda/Kaseda" },
  { id: 157, value: "Castej\u00f3n" },
  { id: 158, value: "Castillo-Nuevo/Gazteluberri" },
  { id: 159, value: "Cintru\u00e9nigo" },
  { id: 160, value: "Ziordia" },
  { id: 161, value: "Cirauqui <> Zirauki/Zirauki" },
  { id: 162, value: "Ciriza <> Ziritza/Ziritza" },
  { id: 163, value: "Cizur/Zizur" },
  { id: 164, value: "Corella" },
  { id: 165, value: "Cortes" },
  { id: 166, value: "Desojo/Desoio" },
  { id: 167, value: "Dicastillo/Deikaztelu" },
  { id: 168, value: "Donamaria" },
  { id: 169, value: "Etxalar" },
  { id: 170, value: "Etxarri /Etxarri" },
  { id: 171, value: "Etxarri-Aranatz/Etxarri Aranatz" },
  { id: 172, value: "Etxauri" },
  { id: 173, value: "Eg\u00fc\u00e9s/Eguesibar" },
  { id: 174, value: "Elgorriaga" },
  {
    id: 175,
    value: "No\u00e1in (Valle De Elorz) <> Noain (Elortzibar)/Noain Elortzibar"
  },
  { id: 176, value: "En\u00e9riz <> Eneritz/Eneritz" },
  { id: 177, value: "Eratsun" },
  { id: 178, value: "Ergoiena" },
  { id: 179, value: "Erro/Erroibar" },
  { id: 180, value: "Ezc\u00e1roz <> Ezkaroze/Ezkaroze" },
  { id: 181, value: "Eslava/Eslaba" },
  { id: 182, value: "Esparza De Salazar <> Espartza Zaraitzu/Espartza" },
  { id: 183, value: "Espronceda/Esprontzeda" },
  { id: 184, value: "Estella <> Lizarra/Lizarra" },
  { id: 185, value: "Esteribar" },
  { id: 186, value: "Etayo/Etaiu" },
  { id: 187, value: "Eulate" },
  { id: 188, value: "Ezcabarte/Ezkabarte" },
  { id: 189, value: "Ezkurra" },
  { id: 190, value: "Ezprogui/Ezporogi" },
  { id: 191, value: "Falces/Faltzes" },
  { id: 192, value: "Fitero" },
  { id: 193, value: "Fontellas" },
  { id: 194, value: "Funes" },
  { id: 195, value: "Fusti\u00f1ana" },
  { id: 196, value: "Galar" },
  { id: 197, value: "Gallipienzo <> Galipentzu/Galipentzu" },
  { id: 198, value: "Gallu\u00e9s <> Galoze/Galoze" },
  { id: 199, value: "Garaioa" },
  { id: 200, value: "Garde" },
  { id: 201, value: "Gar\u00ednoain/Garinoain" },
  { id: 202, value: "Garralda" },
  { id: 203, value: "Genevilla" },
  { id: 204, value: "Goizueta" },
  { id: 205, value: "Go\u00f1i/Go\u00f1erri" },
  { id: 206, value: "G\u00fcesa <> Gorza/Gorza" },
  { id: 207, value: "Gues\u00e1laz <> Gesalatz/Gesalatz" },
  { id: 208, value: "Guirguillano/Girgillao" },
  { id: 209, value: "Huarte <> Uharte/Uharte" },
  { id: 210, value: "Uharte-Arakil/Uharte Arakil" },
  { id: 211, value: "Ibargoiti" },
  { id: 212, value: "Ig\u00fazquiza/Iguzkitza" },
  { id: 213, value: "Imotz" },
  { id: 214, value: "Ira\u00f1eta" },
  { id: 215, value: "Isaba <> Izaba/Izaba" },
  { id: 216, value: "Ituren" },
  { id: 217, value: "Iturmendi" },
  { id: 218, value: "Iza/Itza" },
  { id: 219, value: "Izagaondoa/Itzagaondoa" },
  { id: 220, value: "Izalzu <> Itzaltzu/Itzaltzu" },
  { id: 221, value: "Jaurrieta" },
  { id: 222, value: "Javier/Xabier" },
  { id: 223, value: "Juslape\u00f1a/Txulapain" },
  { id: 224, value: "Labaien" },
  { id: 225, value: "Lakuntza" },
  { id: 226, value: "Lana" },
  { id: 227, value: "Lantz" },
  { id: 228, value: "Lapoblaci\u00f3n" },
  { id: 229, value: "Larraga" },
  { id: 230, value: "Larraona/Larragoa" },
  { id: 231, value: "Larraun" },
  { id: 232, value: "Lazagurr\u00eda/Elizagorria" },
  { id: 233, value: "Leache/Leatxe" },
  { id: 234, value: "Legarda" },
  { id: 235, value: "Legaria" },
  { id: 236, value: "Leitza" },
  { id: 237, value: "Leoz <> Leotz/Leotz" },
  { id: 238, value: "Lerga" },
  { id: 239, value: "Ler\u00edn/Lerin" },
  { id: 240, value: "Lesaka" },
  { id: 241, value: "Lez\u00e1un/Lezaun" },
  { id: 242, value: "Li\u00e9dena/Ledea" },
  { id: 243, value: "Lizoain-Arriasgoiti/Lizoainibar-Arriasgoiti" },
  { id: 244, value: "Lodosa" },
  { id: 245, value: "L\u00f3nguida <> Longida/Longida" },
  { id: 246, value: "Lumbier/Irunberri" },
  { id: 247, value: "Luquin/Lukin" },
  { id: 248, value: "Ma\u00f1eru" },
  { id: 249, value: "Mara\u00f1\u00f3n" },
  { id: 250, value: "Marcilla/Martzilla" },
  { id: 251, value: "M\u00e9lida" },
  { id: 252, value: "Mendavia/Mendabia" },
  { id: 253, value: "Mendaza" },
  { id: 254, value: "Mendigorr\u00eda/Mendigorria" },
  { id: 255, value: "Metauten" },
  { id: 256, value: "Milagro" },
  { id: 257, value: "Mirafuentes" },
  { id: 258, value: "Miranda De Arga/Miranda Arga" },
  { id: 259, value: "Monreal <> Elo/Elo" },
  { id: 260, value: "Monteagudo" },
  { id: 261, value: "Morentin" },
  { id: 262, value: "Mu\u00e9s/Mues" },
  { id: 263, value: "Murchante" },
  { id: 264, value: "Murieta" },
  { id: 265, value: "Murillo El Cuende" },
  { id: 266, value: "Murillo El Fruto" },
  { id: 267, value: "Muruz\u00e1bal/Muruzabal" },
  { id: 268, value: "Navascu\u00e9s/Nabaskoze" },
  { id: 269, value: "Nazar" },
  { id: 270, value: "Obanos" },
  { id: 271, value: "Oco/Oko" },
  { id: 272, value: "Ochagav\u00eda <> Otsagabia/Otsagabia" },
  { id: 273, value: "Odieta" },
  { id: 274, value: "Oitz/Oiz" },
  { id: 275, value: "Ol\u00e1ibar/Olaibar" },
  { id: 276, value: "Olazti/Olazagut\u00eda/Olatzagutia" },
  { id: 277, value: "Olejua/Olexoa" },
  { id: 278, value: "Olite <> Erriberri/Erriberri" },
  { id: 279, value: "Ol\u00f3riz/Oloritz" },
  { id: 280, value: "Cendea De Olza <> Oltza Zendea/Oltza Zendea" },
  { id: 281, value: "Ollo/Ollaran" },
  { id: 282, value: "Orbaizeta" },
  { id: 283, value: "Orbara" },
  { id: 284, value: "Or\u00edsoain/Orisoain" },
  { id: 285, value: "Oronz <> Orontze/Orontze" },
  { id: 286, value: "Oroz-Betelu <> Orotz-Betelu/Orotz-Betelu" },
  { id: 287, value: "Oteiza/Oteitza" },
  { id: 288, value: "Pamplona/Iru\u00f1a/Iru\u00f1ea" },
  { id: 289, value: "Peralta <> Azkoien/Azkoien" },
  { id: 290, value: "Petilla De Arag\u00f3n/Petilla Aragoi" },
  { id: 291, value: "Piedramillera" },
  { id: 292, value: "Pitillas" },
  { id: 293, value: "Puente La Reina <> Gares/Gares" },
  { id: 294, value: "Pueyo/Puiu" },
  { id: 295, value: "Ribaforada" },
  { id: 296, value: "Romanzado/Erromantzatua" },
  { id: 297, value: "Roncal <> Erronkari/Erronkari" },
  { id: 298, value: "Orreaga/Roncesvalles/Orreaga" },
  { id: 299, value: "Sada/Zare" },
  { id: 300, value: "Sald\u00edas/Saldias" },
  { id: 301, value: "Salinas De Oro <> Jaitz/Jaitz" },
  { id: 302, value: "San Adri\u00e1n" },
  { id: 303, value: "Sang\u00fcesa <> Zangoza/Zangoza" },
  { id: 304, value: "San Mart\u00edn De Unx/San Martin Unx" },
  { id: 305, value: "Sansol/Santsol" },
  { id: 306, value: "Santacara/Santakara" },
  { id: 307, value: "Doneztebe/Santesteban/Doneztebe" },
  { id: 308, value: "Sarri\u00e9s <> Sartze/Sartze" },
  { id: 309, value: "Sartaguda" },
  { id: 310, value: "Sesma" },
  { id: 311, value: "Sorlada" },
  { id: 312, value: "Sunbilla" },
  { id: 313, value: "Tafalla" },
  { id: 314, value: "Tiebas-Muruarte De Reta/Tebas-Muru Artederreta" },
  { id: 315, value: "Tirapu" },
  { id: 316, value: "Torralba Del R\u00edo" },
  { id: 317, value: "Torres Del R\u00edo" },
  { id: 318, value: "Tudela/Tutera" },
  { id: 319, value: "Tulebras" },
  { id: 320, value: "\u00dacar/Ukar" },
  { id: 321, value: "Uju\u00e9/Uxue" },
  { id: 322, value: "Ultzama" },
  { id: 323, value: "Unciti/Untzitibar" },
  { id: 324, value: "Unzu\u00e9 <> Untzue/Untzue" },
  { id: 325, value: "Urdazubi/Urdax/Urdazubi" },
  { id: 326, value: "Urdiain" },
  { id: 327, value: "Urra\u00fal Alto/Urraulgoiti" },
  { id: 328, value: "Urra\u00fal Bajo/Urraulbeiti" },
  { id: 329, value: "Urrotz/Urroz" },
  { id: 330, value: "Urroz-Villa/Urrotz" },
  { id: 331, value: "Urzainqui <> Urzainki/Urzainki" },
  { id: 332, value: "Uterga" },
  { id: 333, value: "Uzt\u00e1rroz <> Uztarroze/Uztarroze" },
  { id: 334, value: "Luzaide / Valcarlos/Luzaide" },
  { id: 335, value: "Valtierra" },
  { id: 336, value: "Bera" },
  { id: 337, value: "Viana" },
  { id: 338, value: "Vid\u00e1ngoz <> Bidankoze/Bidankoze" },
  { id: 339, value: "Bidaurreta" },
  { id: 340, value: "Villafranca/Alesbes" },
  { id: 341, value: "Villamayor De Monjard\u00edn" },
  { id: 342, value: "Hiriberri/Villanueva De Aezkoa/Hiriberri" },
  { id: 343, value: "Villatuerta" },
  { id: 344, value: "Villava / Atarrabia/Atarrabia" },
  { id: 345, value: "Igantzi" },
  { id: 346, value: "Valle De Yerri <> Deierri/Deierri" },
  { id: 347, value: "Yesa/Esa" },
  { id: 348, value: "Zabalza <> Zabaltza/Zabaltza" },
  { id: 349, value: "Zubieta" },
  { id: 350, value: "Zugarramurdi" },
  { id: 351, value: "Z\u00fa\u00f1iga/ Zu\u00f1iga" },
  { id: 352, value: "Bara\u00f1\u00e1in/Bara\u00f1ain" },
  { id: 353, value: "Berrioplano <> Berriobeiti/Berriobeiti" },
  { id: 354, value: "Berriozar" },
  { id: 355, value: "Irurtzun" },
  { id: 356, value: "Beri\u00e1in/Beriain" },
  { id: 357, value: "Orkoien" },
  { id: 358, value: "Zizur Mayor <> Zizur Nagusia/Zizur Nagusia" },
  { id: 359, value: "Lekunberri" },
  { id: 360, value: "Valle De Villaverde/Villaverde Turtzioz" },
  { id: 361, value: "Abadi\u00f1o" },
  { id: 362, value: "Abanto Y Ci\u00e9rvana-Abanto Zierbena/Abanto" },
  { id: 363, value: "Amorebieta-Etxano / Zornotza" },
  { id: 364, value: "Amoroto" },
  { id: 365, value: "Arakaldo" },
  { id: 366, value: "Arantzazu" },
  { id: 367, value: "Munitibar-Arbatzegi Gerrikaitz-/Munitibar" },
  { id: 368, value: "Artzentales" },
  { id: 369, value: "Arrankudiaga" },
  { id: 370, value: "Arrieta" },
  { id: 371, value: "Arrigorriaga" },
  { id: 372, value: "Bakio" },
  { id: 373, value: "Barakaldo" },
  { id: 374, value: "Barrika" },
  { id: 375, value: "Basauri" },
  { id: 376, value: "Berango" },
  { id: 377, value: "Bermeo" },
  { id: 378, value: "Berriatua" },
  { id: 379, value: "Berriz" },
  { id: 380, value: "Bilbao/Bilbo" },
  { id: 381, value: "Busturia" },
  { id: 382, value: "Karrantza Harana / Valle De Carranza/Karrantza" },
  { id: 383, value: "Artea/Arteaga" },
  { id: 384, value: "Zeanuri" },
  { id: 385, value: "Zeberio" },
  { id: 386, value: "Dima" },
  { id: 387, value: "Durango" },
  { id: 388, value: "Ea" },
  { id: 389, value: "Etxebarri" },
  { id: 390, value: "Etxebarria" },
  { id: 391, value: "Elantxobe" },
  { id: 392, value: "Elorrio" },
  { id: 393, value: "Ere\u00f1o" },
  { id: 394, value: "Ermua" },
  { id: 395, value: "Fruiz" },
  { id: 396, value: "Galdakao" },
  { id: 397, value: "Galdames" },
  { id: 398, value: "Gamiz-Fika" },
  { id: 399, value: "Garai" },
  { id: 400, value: "Gatika" },
  { id: 401, value: "Gautegiz Arteaga" },
  { id: 402, value: "Gordexola" },
  { id: 403, value: "Gorliz" },
  { id: 404, value: "Getxo" },
  { id: 405, value: "G\u00fce\u00f1es/Gue\u00f1es" },
  { id: 406, value: "Gernika-Lumo" },
  { id: 407, value: "Gizaburuaga" },
  { id: 408, value: "Ibarrangelu" },
  { id: 409, value: "Ispaster" },
  { id: 410, value: "Izurtza" },
  { id: 411, value: "Lanestosa" },
  { id: 412, value: "Larrabetzu" },
  { id: 413, value: "Laukiz" },
  { id: 414, value: "Leioa" },
  { id: 415, value: "Lemoa" },
  { id: 416, value: "Lemoiz" },
  { id: 417, value: "Lekeitio" },
  { id: 418, value: "Mallabia" },
  { id: 419, value: "Ma\u00f1aria" },
  { id: 420, value: "Markina-Xemein" },
  { id: 421, value: "Maruri-Jatabe/Jatabe" },
  { id: 422, value: "Mendata" },
  { id: 423, value: "Mendexa" },
  { id: 424, value: "Me\u00f1aka" },
  { id: 425, value: "Ugao-Miraballes/Ugao" },
  { id: 426, value: "Morga" },
  { id: 427, value: "Muxika" },
  { id: 428, value: "Mundaka" },
  { id: 429, value: "Mungia" },
  { id: 430, value: "Aulesti" },
  { id: 431, value: "Muskiz" },
  { id: 432, value: "Otxandio" },
  { id: 433, value: "Ondarroa" },
  { id: 434, value: "Urdu\u00f1a / Ordu\u00f1a/Urdu\u00f1a" },
  { id: 435, value: "Orozko" },
  { id: 436, value: "Sukarrieta" },
  { id: 437, value: "Plentzia" },
  { id: 438, value: "Portugalete" },
  { id: 439, value: "Errigoiti" },
  { id: 440, value: "Valle De Tr\u00e1paga-Trapagaran/Trapagaran" },
  { id: 441, value: "Lezama" },
  { id: 442, value: "Santurtzi" },
  { id: 443, value: "Ortuella" },
  { id: 444, value: "Sestao" },
  { id: 445, value: "Sopelana/Sopela" },
  { id: 446, value: "Sopuerta" },
  { id: 447, value: "Trucios-Turtzioz/Turtzioz" },
  { id: 448, value: "Ubide" },
  { id: 449, value: "Urd\u00faliz/Urduliz" },
  { id: 450, value: "Balmaseda" },
  { id: 451, value: "Atxondo" },
  { id: 452, value: "Bedia" },
  { id: 453, value: "Areatza" },
  { id: 454, value: "Igorre" },
  { id: 455, value: "Zaldibar" },
  { id: 456, value: "Zalla" },
  { id: 457, value: "Zaratamo" },
  { id: 458, value: "Derio" },
  { id: 459, value: "Erandio" },
  { id: 460, value: "Loiu" },
  { id: 461, value: "Sondika" },
  { id: 462, value: "Zamudio" },
  { id: 463, value: "Forua" },
  { id: 464, value: "Kortezubi" },
  { id: 465, value: "Murueta" },
  { id: 466, value: "Nabarniz" },
  { id: 467, value: "Iurreta" },
  { id: 468, value: "Ajangiz" },
  { id: 469, value: "Alonsotegi" },
  { id: 470, value: "Zierbena" },
  { id: 471, value: "Arratzu" },
  { id: 472, value: "Ziortza-Bolibar" },
  { id: 473, value: "Ahaxe-Alciette-Bascassan/Ahatsa-Altzieta-Bazkazane" },
  { id: 474, value: "Ahetze" },
  { id: 475, value: "A\u00efcirits-Camou-Suhast/Aiziritze-Gamue-Zohazti" },
  { id: 476, value: "Aincille/Aintzila" },
  { id: 477, value: "A\u00efnharp/Ainharbe" },
  { id: 478, value: "Ainhice-Mongelos/Ainhize-Monjolose" },
  { id: 479, value: "A\u00efnharp/Ainhoa" },
  {
    id: 480,
    value:
      "Al\u00e7ay-Al\u00e7ab\u00e9h\u00e9ty-Sunharette/Altzai-Altzabeheti-Zunharreta"
  },
  { id: 481, value: "Les Aldudes/Aldude" },
  { id: 482, value: "Alos-Sibas-Abense/Aloze-Ziboze-Onizegaine" },
  { id: 483, value: "Amendeuix-Oneix/Amend\u00fcze-Unaso" },
  { id: 484, value: "Amorots-Succos/Amorotze-Zokotze" },
  { id: 485, value: "Anglet/Angelu" },
  { id: 486, value: "Anhaux/Anhauze" },
  { id: 487, value: "Arancou/Erango" },
  { id: 488, value: "Arb\u00e9rats-Sill\u00e8gue/Arberatze-Zilhekoa" },
  { id: 489, value: "Arbonne/Arbona" },
  { id: 490, value: "Arbouet-Sussaute/Arboti-Zohota" },
  { id: 491, value: "Arcangues/Arrangoitze" },
  { id: 492, value: "Arhansus/Arhantsusi" },
  { id: 493, value: "Armendarits/Armendaritze" },
  { id: 494, value: "Arn\u00e9guy/Arnegi" },
  {
    id: 495,
    value: "Aroue-Ithorots-Olha\u00efby/Ar\u00fce-Ithorrotze-Olhaibi"
  },
  { id: 496, value: "Arrast-Larrebieu/\u00dcrr\u00fcstoi-Larrabile" },
  { id: 497, value: "Arraute-Charritte/Arrueta-Sarrikota" },
  { id: 498, value: "Ascain/Azkaine" },
  { id: 499, value: "Ascarat/Azkarate" },
  { id: 500, value: "Aussurucq/Altz\u00fcr\u00fck\u00fc" },
  { id: 501, value: "Ayherre/Aiherra" },
  { id: 502, value: "Banca/Banka" },
  { id: 503, value: "Barcus/Barkoxe" },
  { id: 504, value: "Bardos/Bardoze" },
  { id: 505, value: "Bassussarry/Basusarri" },
  { id: 506, value: "Bayonne/Baiona" },
  { id: 507, value: "B\u00e9guios/Behauze" },
  { id: 508, value: "B\u00e9hasque-Lapiste/Behaskane-Laphizketa" },
  { id: 509, value: "B\u00e9horl\u00e9guy/Behorlegi" },
  { id: 510, value: "Bergouey-Viellenave/Burgue-Erreiti" },
  { id: 511, value: "Berrogain-Laruns/Berrogaine-Lar\u00fcntze" },
  { id: 512, value: "Beyrie-Sur-Joyeuse/Bithiri\u00f1a" },
  { id: 513, value: "Biarritz" },
  { id: 514, value: "Bidache/Bidaxune" },
  { id: 515, value: "Bidarray/Bidarrai" },
  { id: 516, value: "Bidart/Bidarte" },
  { id: 517, value: "Biriatou/Biriatu" },
  { id: 518, value: "Bonloc/Lekuine" },
  { id: 519, value: "Boucau/Bokale" },
  { id: 520, value: "Briscous/Beskoitze" },
  { id: 521, value: "Bunus/Bunuze" },
  { id: 522, value: "Bussunarits-Sarrasquette/Duzunaritze-Sarasketa" },
  { id: 523, value: "Bustince-Iriberry/Buztintze-Hiriberri" },
  { id: 524, value: "Cambo-Les-Bains/Kanbo" },
  { id: 525, value: "Came/Akamarre" },
  { id: 526, value: "Camou-Cihigue/Gamere-Zihiga" },
  { id: 527, value: "\u00c7aro/Zaro" },
  { id: 528, value: "Charritte-De-Bas/Sarrikotapea" },
  { id: 529, value: "Ch\u00e9raute/Soh\u00fcta" },
  { id: 530, value: "Ciboure/Ziburu" },
  { id: 531, value: "Domezain-Berraute/Domintxaine-Berroeta" },
  { id: 532, value: "Espelette/Ezpeleta" },
  { id: 533, value: "Esp\u00e8s-Undurein/Ezpeize-\u00dcnd\u00fcreine" },
  { id: 534, value: "Esquiule/Eskiula" },
  { id: 535, value: "Est\u00e9ren\u00e7uby/Ezterenzubi" },
  { id: 536, value: "Etcharry/Etxarri" },
  { id: 537, value: "Etchebar/Etxebarre" },
  { id: 538, value: "Gabat/Gabadi" },
  { id: 539, value: "Gamarthe/Gamarte" },
  { id: 540, value: "Garindein/Garindaine" },
  { id: 541, value: "Garris/Garr\u00fcze" },
  { id: 542, value: "Gestas/Jeztaze" },
  { id: 543, value: "Gotein-Libarrenx/Gotaine-Irabarne" },
  { id: 544, value: "Gu\u00e9thary/Getaria" },
  { id: 545, value: "Guiche/Gixune" },
  { id: 546, value: "Halsou/Haltsu" },
  { id: 547, value: "Hasparren/Hazparne" },
  { id: 548, value: "Haux/Hauze" },
  { id: 549, value: "H\u00e9lette/Heleta" },
  { id: 550, value: "Hendaye/Hendaia" },
  { id: 551, value: "L'h\u00f4pital-Saint-Blaise/Ospitalepea" },
  { id: 552, value: "Hosta/Hozta" },
  { id: 553, value: "Ibarrolle/Ibarrola" },
  { id: 554, value: "Idaux-Mendy/Idauze-Mendi" },
  { id: 555, value: "Iholdy/Iholdi" },
  { id: 556, value: "Ilharre" },
  { id: 557, value: "Irissarry/Irisarri" },
  { id: 558, value: "Iroul\u00e9guy/Irulegi" },
  { id: 559, value: "Ispoure/Izpura" },
  { id: 560, value: "Isturits/Izturitze" },
  { id: 561, value: "Itxassou/Itsasu" },
  { id: 562, value: "Jatxou/Jatsu" },
  { id: 563, value: "Jaxu/Jatsu" },
  { id: 564, value: "Juxue/Jutsi" },
  { id: 565, value: "Labastide-Clairence/Bastida" },
  { id: 566, value: "Labets-Biscay/Labetze-Bizkai" },
  { id: 567, value: "Lacarre/Lakarra" },
  {
    id: 568,
    value: "Lacarry-Arhan-Charritte-De-Haut/Lakarri-Arhane-Sarrikotagaine"
  },
  { id: 569, value: "Laguinge-Restoue/Liginaga-Ast\u00fce" },
  { id: 570, value: "Lahonce/Lehuntze" },
  { id: 571, value: "Lantabat/Landibarre" },
  { id: 572, value: "Larceveau-Arros-Cibits/Larzabale-Arroze-Zibitze" },
  { id: 573, value: "Larrau/Larraine" },
  { id: 574, value: "Larressore/Larresoro" },
  { id: 575, value: "Larribar-Sorhapuru/Larribarre-Sorhap\u00fcr\u00fc" },
  { id: 576, value: "Lasse/Lasa" },
  { id: 577, value: "Lecumberry/Lekunberri" },
  { id: 578, value: "Lichans-Sunhar/Lexantz\u00fc-Zunharre" },
  { id: 579, value: "Licq-Ath\u00e9rey/Ligi-Atherei" },
  { id: 580, value: "Lohitzun-Oyhercq/Lohitz\u00fcne-Oihergi" },
  { id: 581, value: "Louhossoa/Luhuso" },
  { id: 582, value: "Luxe-Sumberraute/L\u00fck\u00fcze-Altz\u00fcmarta" },
  { id: 583, value: "Macaye/Makea" },
  { id: 584, value: "Masparraute/Martxueta" },
  { id: 585, value: "Maul\u00e9on-Licharre/Maule-Lextarre" },
  { id: 586, value: "M\u00e9harin/Mehaine" },
  { id: 587, value: "Mendionde/Lekorne" },
  { id: 588, value: "Menditte/Mendikota" },
  { id: 589, value: "Mendive/Mendibe" },
  { id: 590, value: "Moncayolle-Larrory-Mendibieu/Mitikile-Larrori-Mendibile" },
  { id: 591, value: "Montory/Montori" },
  { id: 592, value: "Mouguerre/Mugerre" },
  { id: 593, value: "Musculdy/Muskildi" },
  { id: 594, value: "Ordiarp/Urdi\u00f1arbe" },
  { id: 595, value: "Or\u00e8gue/Oragarre" },
  { id: 596, value: "Orsanco/Ostankoa" },
  { id: 597, value: "Ossas-Suhare/Ozaze-Z\u00fchara" },
  { id: 598, value: "Osserain-Rivareyte/Ozaraine-Erribareita" },
  { id: 599, value: "Oss\u00e8s/Ortzaize" },
  { id: 600, value: "Ostabat-Asme/Izura-Azme" },
  { id: 601, value: "Pagolle/Pagola" },
  { id: 602, value: "Roquiague/Arrokiaga" },
  { id: 603, value: "Sainte-Engr\u00e2ce/Urdatx" },
  { id: 604, value: "Saint-Esteben/Donoztiri" },
  { id: 605, value: "Saint-\u00c9tienne-De-Ba\u00efgorry/Baigorri" },
  { id: 606, value: "Saint-Jean-De-Luz/Donibane Lohizune" },
  { id: 607, value: "Saint-Jean-Le-Vieux/Donazaharre" },
  { id: 608, value: "Saint-Jean-Pied-De-Port/Donibane Garazi" },
  { id: 609, value: "Saint-Just-Ibarre/Donaixti-Ibarre" },
  { id: 610, value: "Saint-Martin-D'arb\u00e9roue/Donamartiri" },
  { id: 611, value: "Saint-Martin-D'arrossa/Arrosa" },
  { id: 612, value: "Saint-Michel/Eiheralarre" },
  { id: 613, value: "Saint-Palais/Donapaleu" },
  { id: 614, value: "Saint-P\u00e9e-Sur-Nivelle/Senpere" },
  { id: 615, value: "Saint-Pierre-D'irube/Hiriburu" },
  { id: 616, value: "Sames/Samatze" },
  { id: 617, value: "Sare/Sara" },
  { id: 618, value: "Sauguis-Saint-\u00c9tienne/Zalgize-Doneztebe" },
  { id: 619, value: "Soura\u00efde / Zuraide" },
  { id: 620, value: "Suhescun/Suhuskune" },
  { id: 621, value: "Tardets-Sorholus/Atharratze-Sorhol\u00fcze" },
  { id: 622, value: "Trois-Villes/Iruri" },
  { id: 623, value: "Uhart-Cize/Uharte Garazi" },
  { id: 624, value: "Uhart-Mixe/Uhartehiri" },
  { id: 625, value: "Urcuit/Urketa" },
  { id: 626, value: "Urepel/Urepele" },
  { id: 627, value: "Urrugne/Urru\u00f1a" },
  { id: 628, value: "Urt/Ahurti" },
  { id: 629, value: "Ustaritz/Uztaritze" },
  { id: 630, value: "Villefranque/Milafranga" },
  { id: 631, value: "Viodos-Abense-De-Bas/Bildoze-Onizepea" },
  { id: 632, value: "Alegr\u00eda-Dulantzi/Dulantzi" },
  { id: 633, value: "Amurrio" },
  { id: 634, value: "Aramaio" },
  { id: 635, value: "Artziniega" },
  { id: 636, value: "Armi\u00f1\u00f3n" },
  { id: 637, value: "Arrazua-Ubarrundia/Arratzua-Ubarrundia" },
  { id: 638, value: "Asparrena" },
  { id: 639, value: "Ayala/Aiara/Aiara" },
  { id: 640, value: "Ba\u00f1os De Ebro/Ma\u00f1ueta/Ma\u00f1ueta" },
  { id: 641, value: "Barrundia" },
  { id: 642, value: "Berantevilla" },
  { id: 643, value: "Bernedo" },
  { id: 644, value: "Campezo/Kanpezu/Kanpezu" },
  { id: 645, value: "Zigoitia" },
  { id: 646, value: "Kripan" },
  { id: 647, value: "Kuartango" },
  { id: 648, value: "Elburgo/Burgelu/Burgu" },
  { id: 649, value: "Elciego/Eltziego" },
  { id: 650, value: "Elvillar / Bilar/Bilar" },
  { id: 651, value: "Iruraiz-Gauna/Iruraitz-Gauna" },
  { id: 652, value: "Labastida / Bastida/Bastida" },
  { id: 653, value: "Lagr\u00e1n/Lagran" },
  { id: 654, value: "Laguardia/Guardia" },
  { id: 655, value: "Lanciego/Lantziego/Lantziego" },
  { id: 656, value: "Lapuebla De Labarca" },
  { id: 657, value: "Leza" },
  { id: 658, value: "Laudio / Llodio/Laudio" },
  { id: 659, value: "Arraia-Maeztu" },
  { id: 660, value: "Moreda De \u00c1lava / Moreda Araba/Moreda" },
  { id: 661, value: "Navaridas" },
  { id: 662, value: "Okondo" },
  { id: 663, value: "Oy\u00f3n-Oion/Oion" },
  { id: 664, value: "Pe\u00f1acerrada-Urizaharra/Urizaharra" },
  { id: 665, value: "Erriberagoitia / Ribera Alta/Erriberagoitia" },
  { id: 666, value: "Ribera Baja / Erribera Beitia/Erriberabeitia" },
  { id: 667, value: "A\u00f1ana" },
  { id: 668, value: "Agurain / Salvatierra/Agurain" },
  { id: 669, value: "Samaniego" },
  { id: 670, value: "San Mill\u00e1n/Donemiliaga/Donemiliaga" },
  { id: 671, value: "Urkabustaiz" },
  { id: 672, value: "Valdegov\u00eda / Gaubea/Gaubea" },
  { id: 673, value: "Harana/Valle De Arana/Harana" },
  { id: 674, value: "Villabuena De \u00c1lava / Eskuernaga/Villabuena" },
  { id: 675, value: "Legutio" },
  { id: 676, value: "Vitoria-Gasteiz/Gasteiz" },
  { id: 677, value: "Y\u00e9cora / Iekora/Ekora" },
  { id: 678, value: "Zalduondo" },
  { id: 679, value: "Zambrana/Zanbrana" },
  { id: 680, value: "Zuia" },
  { id: 681, value: "Iru\u00f1a Oka/Iru\u00f1a De Oca/Iru\u00f1a Oka" },
  { id: 682, value: "Lantar\u00f3n" },
  { id: 683, value: "Condado De Trevi\u00f1o/Trebi\u00f1u" },
  { id: 684, value: "La Puebla De Arganz\u00f3n/Argantzun" }
];
