export default ["Abaltzisketa",
"Aduna",
"Aizarnazabal",
"Albiztur",
"Alegia",
"Alkiza",
"Altzo",
"Amezketa",
"Andoain",
"Anoeta",
"Antzuola",
"Arama",
"Aretxabaleta",
"Asteasu",
"Ataun",
"Aia",
"Azkoitia",
"Azpeitia",
"Beasain",
"Beizama",
"Belauntza",
"Berastegi",
"Berrobi",
"Bidegoian/Bidania-Goiatz",
"Zegama",
"Zerain",
"Zestoa",
"Zizurkil",
"Deba",
"Eibar",
"Elduain",
"Elgoibar",
"Elgeta",
"Eskoriatza",
"Ezkio-Itsaso",
"Hondarribia",
"Gaintza",
"Gabiria",
"Getaria",
"Hernani",
"Hernialde",
"Ibarra",
"Idiazabal",
"Ikaztegieta",
"Irun",
"Irura",
"Itsasondo",
"Larraul",
"Lazkao",
"Leaburu",
"Legazpi",
"Legorreta",
"Lezo",
"Lizartza",
"Arrasate/Mondragón/Arrasate",
"Mutriku",
"Mutiloa",
"Olaberria",
"Oñati",
"Orexa",
"Orio",
"Ormaiztegi",
"Oiartzun",
"Pasaia",
"Soraluze-Placencia De Las Armas/Soraluze",
"Errezil",
"Errenteria",
"Leintz-Gatzaga/Leintz Gatzaga",
"Donostia-San Sebastián/Donostia",
"Segura",
"Tolosa",
"Urnieta",
"Usurbil",
"Bergara",
"Villabona/Villabona-Amasa",
"Ordizia",
"Urretxu",
"Zaldibia",
"Zarautz",
"Zumarraga",
"Zumaia",
"Mendaro",
"Lasarte-Oria",
"Astigarraga",
"Baliarrain",
"Orendain",
"Altzaga",
"Gaztelu",
"Abáigar/Abaigar",
"Abárzuza <> Abartzuza/Abartzuza",
"Abaurregaina/Abaurrea Alta/Abaurregaina",
"Abaurrepea/Abaurrea Baja/Abaurrepea",
"Aberin",
"Ablitas",
"Adiós/Adios",
"Aguilar De Codés/Aguilar Kodes",
"Aibar <> Oibar/Oibar",
"Altsasu/Alsasua/Altsasu",
"Allín <> Allin/Allin",
"Allo",
"Améscoa Baja/Ameskoabarrena",
"Ancín <> Antzin/Antzin",
"Andosilla",
"Ansoáin <> Antsoain/Antsoain",
"Anue",
"Añorbe",
"Aoiz/Agoitz/Agoitz",
"Araitz",
"Aranarache <> Aranaratxe/Aranaratxe",
"Arantza",
"Aranguren",
"Arano",
"Arakil",
"Aras",
"Arbizu",
"Arce <> Artzi/Artzibar",
"Los Arcos",
"Arellano",
"Areso",
"Arguedas",
"Aria",
"Aribe",
"Armañanzas/Armañantzas",
"Arróniz/Arroitz",
"Arruazu",
"Artajona/Artaxoa",
"Artazu",
"Atez/Atetz",
"Ayegui <> Aiegi/Aiegi",
"Azagra",
"Azuelo",
"Bakaiku",
"Barásoain/Barasoain",
"Barbarin",
"Bargota",
"Barillas",
"Basaburua",
"Baztan",
"Beire",
"Belascoáin/Beraskoain",
"Berbinzana/Berbintzana",
"Bertizarana",
"Betelu",
"Biurrun-Olcoz/Biurrun-Olkotz",
"Buñuel",
"Auritz/Burguete/Auritz",
"Burgui <> Burgi/Burgi",
"Burlada <> Burlata/Burlata",
"El Busto",
"Cabanillas",
"Cabredo",
"Cadreita",
"Caparroso",
"Cárcar",
"Carcastillo/Zarrakaztelu",
"Cascante",
"Cáseda/Kaseda",
"Castejón",
"Castillo-Nuevo/Gazteluberri",
"Cintruénigo",
"Ziordia",
"Cirauqui <> Zirauki/Zirauki",
"Ciriza <> Ziritza/Ziritza",
"Cizur/Zizur",
"Corella",
"Cortes",
"Desojo/Desoio",
"Dicastillo/Deikaztelu",
"Donamaria",
"Etxalar",
"Etxarri /Etxarri",
"Etxarri-Aranatz/Etxarri Aranatz",
"Etxauri",
"Egüés/Eguesibar",
"Elgorriaga",
"Noáin (Valle De Elorz) <> Noain (Elortzibar)/Noain Elortzibar",
"Enériz <> Eneritz/Eneritz",
"Eratsun",
"Ergoiena",
"Erro/Erroibar",
"Ezcároz <> Ezkaroze/Ezkaroze",
"Eslava/Eslaba",
"Esparza De Salazar <> Espartza Zaraitzu/Espartza",
"Espronceda/Esprontzeda",
"Estella <> Lizarra/Lizarra",
"Esteribar",
"Etayo/Etaiu",
"Eulate",
"Ezcabarte/Ezkabarte",
"Ezkurra",
"Ezprogui/Ezporogi",
"Falces/Faltzes",
"Fitero",
"Fontellas",
"Funes",
"Fustiñana",
"Galar",
"Gallipienzo <> Galipentzu/Galipentzu",
"Gallués <> Galoze/Galoze",
"Garaioa",
"Garde",
"Garínoain/Garinoain",
"Garralda",
"Genevilla",
"Goizueta",
"Goñi/Goñerri",
"Güesa <> Gorza/Gorza",
"Guesálaz <> Gesalatz/Gesalatz",
"Guirguillano/Girgillao",
"Huarte <> Uharte/Uharte",
"Uharte-Arakil/Uharte Arakil",
"Ibargoiti",
"Igúzquiza/Iguzkitza",
"Imotz",
"Irañeta",
"Isaba <> Izaba/Izaba",
"Ituren",
"Iturmendi",
"Iza/Itza",
"Izagaondoa/Itzagaondoa",
"Izalzu <> Itzaltzu/Itzaltzu",
"Jaurrieta",
"Javier/Xabier",
"Juslapeña/Txulapain",
"Labaien",
"Lakuntza",
"Lana",
"Lantz",
"Lapoblación",
"Larraga",
"Larraona/Larragoa",
"Larraun",
"Lazagurría/Elizagorria",
"Leache/Leatxe",
"Legarda",
"Legaria",
"Leitza",
"Leoz <> Leotz/Leotz",
"Lerga",
"Lerín/Lerin",
"Lesaka",
"Lezáun/Lezaun",
"Liédena/Ledea",
"Lizoain-Arriasgoiti/Lizoainibar-Arriasgoiti",
"Lodosa",
"Lónguida <> Longida/Longida",
"Lumbier/Irunberri",
"Luquin/Lukin",
"Mañeru",
"Marañón",
"Marcilla/Martzilla",
"Mélida",
"Mendavia/Mendabia",
"Mendaza",
"Mendigorría/Mendigorria",
"Metauten",
"Milagro",
"Mirafuentes",
"Miranda De Arga/Miranda Arga",
"Monreal <> Elo/Elo",
"Monteagudo",
"Morentin",
"Mués/Mues",
"Murchante",
"Murieta",
"Murillo El Cuende",
"Murillo El Fruto",
"Muruzábal/Muruzabal",
"Navascués/Nabaskoze",
"Nazar",
"Obanos",
"Oco/Oko",
"Ochagavía <> Otsagabia/Otsagabia",
"Odieta",
"Oitz/Oiz",
"Oláibar/Olaibar",
"Olazti/Olazagutía/Olatzagutia",
"Olejua/Olexoa",
"Olite <> Erriberri/Erriberri",
"Olóriz/Oloritz",
"Cendea De Olza <> Oltza Zendea/Oltza Zendea",
"Ollo/Ollaran",
"Orbaizeta",
"Orbara",
"Orísoain/Orisoain",
"Oronz <> Orontze/Orontze",
"Oroz-Betelu <> Orotz-Betelu/Orotz-Betelu",
"Oteiza/Oteitza",
"Pamplona/Iruña/Iruñea",
"Peralta <> Azkoien/Azkoien",
"Petilla De Aragón/Petilla Aragoi",
"Piedramillera",
"Pitillas",
"Puente La Reina <> Gares/Gares",
"Pueyo/Puiu",
"Ribaforada",
"Romanzado/Erromantzatua",
"Roncal <> Erronkari/Erronkari",
"Orreaga/Roncesvalles/Orreaga",
"Sada/Zare",
"Saldías/Saldias",
"Salinas De Oro <> Jaitz/Jaitz",
"San Adrián",
"Sangüesa <> Zangoza/Zangoza",
"San Martín De Unx/San Martin Unx",
"Sansol/Santsol",
"Santacara/Santakara",
"Doneztebe/Santesteban/Doneztebe",
"Sarriés <> Sartze/Sartze",
"Sartaguda",
"Sesma",
"Sorlada",
"Sunbilla",
"Tafalla",
"Tiebas-Muruarte De Reta/Tebas-Muru Artederreta",
"Tirapu",
"Torralba Del Río",
"Torres Del Río",
"Tudela/Tutera",
"Tulebras",
"Úcar/Ukar",
"Ujué/Uxue",
"Ultzama",
"Unciti/Untzitibar",
"Unzué <> Untzue/Untzue",
"Urdazubi/Urdax/Urdazubi",
"Urdiain",
"Urraúl Alto/Urraulgoiti",
"Urraúl Bajo/Urraulbeiti",
"Urrotz/Urroz",
"Urroz-Villa/Urrotz",
"Urzainqui <> Urzainki/Urzainki",
"Uterga",
"Uztárroz <> Uztarroze/Uztarroze",
"Luzaide / Valcarlos/Luzaide",
"Valtierra",
"Bera",
"Viana",
"Vidángoz <> Bidankoze/Bidankoze",
"Bidaurreta",
"Villafranca/Alesbes",
"Villamayor De Monjardín",
"Hiriberri/Villanueva De Aezkoa/Hiriberri",
"Villatuerta",
"Villava / Atarrabia/Atarrabia",
"Igantzi",
"Valle De Yerri <> Deierri/Deierri",
"Yesa/Esa",
"Zabalza <> Zabaltza/Zabaltza",
"Zubieta",
"Zugarramurdi",
"Zúñiga/ Zuñiga",
"Barañáin/Barañain",
"Berrioplano <> Berriobeiti/Berriobeiti",
"Berriozar",
"Irurtzun",
"Beriáin/Beriain",
"Orkoien",
"Zizur Mayor <> Zizur Nagusia/Zizur Nagusia",
"Lekunberri",
"Valle De Villaverde/Villaverde Turtzioz",
"Abadiño",
"Abanto Y Ciérvana-Abanto Zierbena/Abanto",
"Amorebieta-Etxano / Zornotza",
"Amoroto",
"Arakaldo",
"Arantzazu",
"Munitibar-Arbatzegi Gerrikaitz-/Munitibar",
"Artzentales",
"Arrankudiaga",
"Arrieta",
"Arrigorriaga",
"Bakio",
"Barakaldo",
"Barrika",
"Basauri",
"Berango",
"Bermeo",
"Berriatua",
"Berriz",
"Bilbao/Bilbo",
"Busturia",
"Karrantza Harana / Valle De Carranza/Karrantza",
"Artea/Arteaga",
"Zeanuri",
"Zeberio",
"Dima",
"Durango",
"Ea",
"Etxebarri",
"Etxebarria",
"Elantxobe",
"Elorrio",
"Ereño",
"Ermua",
"Fruiz",
"Galdakao",
"Galdames",
"Gamiz-Fika",
"Garai",
"Gatika",
"Gautegiz Arteaga",
"Gordexola",
"Gorliz",
"Getxo",
"Güeñes/Gueñes",
"Gernika-Lumo",
"Gizaburuaga",
"Ibarrangelu",
"Ispaster",
"Izurtza",
"Lanestosa",
"Larrabetzu",
"Laukiz",
"Leioa",
"Lemoa",
"Lemoiz",
"Lekeitio",
"Mallabia",
"Mañaria",
"Markina-Xemein",
"Maruri-Jatabe/Jatabe",
"Mendata",
"Mendexa",
"Meñaka",
"Ugao-Miraballes/Ugao",
"Morga",
"Muxika",
"Mundaka",
"Mungia",
"Aulesti",
"Muskiz",
"Otxandio",
"Ondarroa",
"Urduña / Orduña/Urduña",
"Orozko",
"Sukarrieta",
"Plentzia",
"Portugalete",
"Errigoiti",
"Valle De Trápaga-Trapagaran/Trapagaran",
"Lezama",
"Santurtzi",
"Ortuella",
"Sestao",
"Sopelana/Sopela",
"Sopuerta",
"Trucios-Turtzioz/Turtzioz",
"Ubide",
"Urdúliz/Urduliz",
"Balmaseda",
"Atxondo",
"Bedia",
"Areatza",
"Igorre",
"Zaldibar",
"Zalla",
"Zaratamo",
"Derio",
"Erandio",
"Loiu",
"Sondika",
"Zamudio",
"Forua",
"Kortezubi",
"Murueta",
"Nabarniz",
"Iurreta",
"Ajangiz",
"Alonsotegi",
"Zierbena",
"Arratzu",
"Ziortza-Bolibar",
"Ahaxe-Alciette-Bascassan/Ahatsa-Altzieta-Bazkazane",
"Ahetze",
"Aïcirits-Camou-Suhast/Aiziritze-Gamue-Zohazti",
"Aincille/Aintzila",
"Aïnharp/Ainharbe",
"Ainhice-Mongelos/Ainhize-Monjolose",
"Aïnharp/Ainhoa",
"Alçay-Alçabéhéty-Sunharette/Altzai-Altzabeheti-Zunharreta",
"Les Aldudes/Aldude",
"Alos-Sibas-Abense/Aloze-Ziboze-Onizegaine",
"Amendeuix-Oneix/Amendüze-Unaso",
"Amorots-Succos/Amorotze-Zokotze",
"Anglet/Angelu",
"Anhaux/Anhauze",
"Arancou/Erango",
"Arbérats-Sillègue/Arberatze-Zilhekoa",
"Arbonne/Arbona",
"Arbouet-Sussaute/Arboti-Zohota",
"Arcangues/Arrangoitze",
"Arhansus/Arhantsusi",
"Armendarits/Armendaritze",
"Arnéguy/Arnegi",
"Aroue-Ithorots-Olhaïby/Arüe-Ithorrotze-Olhaibi",
"Arrast-Larrebieu/Ürrüstoi-Larrabile",
"Arraute-Charritte/Arrueta-Sarrikota",
"Ascain/Azkaine",
"Ascarat/Azkarate",
"Aussurucq/Altzürükü",
"Ayherre/Aiherra",
"Banca/Banka",
"Barcus/Barkoxe",
"Bardos/Bardoze",
"Bassussarry/Basusarri",
"Bayonne/Baiona",
"Béguios/Behauze",
"Béhasque-Lapiste/Behaskane-Laphizketa",
"Béhorléguy/Behorlegi",
"Bergouey-Viellenave/Burgue-Erreiti",
"Berrogain-Laruns/Berrogaine-Larüntze",
"Beyrie-Sur-Joyeuse/Bithiriña",
"Biarritz",
"Bidache/Bidaxune",
"Bidarray/Bidarrai",
"Bidart/Bidarte",
"Biriatou/Biriatu",
"Bonloc/Lekuine",
"Boucau/Bokale",
"Briscous/Beskoitze",
"Bunus/Bunuze",
"Bussunarits-Sarrasquette/Duzunaritze-Sarasketa",
"Bustince-Iriberry/Buztintze-Hiriberri",
"Cambo-Les-Bains/Kanbo",
"Came/Akamarre",
"Camou-Cihigue/Gamere-Zihiga",
"Çaro/Zaro",
"Charritte-De-Bas/Sarrikotapea",
"Chéraute/Sohüta",
"Ciboure/Ziburu",
"Domezain-Berraute/Domintxaine-Berroeta",
"Espelette/Ezpeleta",
"Espès-Undurein/Ezpeize-Ündüreine",
"Esquiule/Eskiula",
"Estérençuby/Ezterenzubi",
"Etcharry/Etxarri",
"Etchebar/Etxebarre",
"Gabat/Gabadi",
"Gamarthe/Gamarte",
"Garindein/Garindaine",
"Garris/Garrüze",
"Gestas/Jeztaze",
"Gotein-Libarrenx/Gotaine-Irabarne",
"Guéthary/Getaria",
"Guiche/Gixune",
"Halsou/Haltsu",
"Hasparren/Hazparne",
"Haux/Hauze",
"Hélette/Heleta",
"Hendaye/Hendaia",
"L'hôpital-Saint-Blaise/Ospitalepea",
"Hosta/Hozta",
"Ibarrolle/Ibarrola",
"Idaux-Mendy/Idauze-Mendi",
"Iholdy/Iholdi",
"Ilharre",
"Irissarry/Irisarri",
"Irouléguy/Irulegi",
"Ispoure/Izpura",
"Isturits/Izturitze",
"Itxassou/Itsasu",
"Jatxou/Jatsu",
"Jaxu/Jatsu",
"Juxue/Jutsi",
"Labastide-Clairence/Bastida",
"Labets-Biscay/Labetze-Bizkai",
"Lacarre/Lakarra",
"Lacarry-Arhan-Charritte-De-Haut/Lakarri-Arhane-Sarrikotagaine",
"Laguinge-Restoue/Liginaga-Astüe",
"Lahonce/Lehuntze",
"Lantabat/Landibarre",
"Larceveau-Arros-Cibits/Larzabale-Arroze-Zibitze",
"Larrau/Larraine",
"Larressore/Larresoro",
"Larribar-Sorhapuru/Larribarre-Sorhapürü",
"Lasse/Lasa",
"Lecumberry/Lekunberri",
"Lichans-Sunhar/Lexantzü-Zunharre",
"Licq-Athérey/Ligi-Atherei",
"Lohitzun-Oyhercq/Lohitzüne-Oihergi",
"Louhossoa/Luhuso",
"Luxe-Sumberraute/Lüküze-Altzümarta",
"Macaye/Makea",
"Masparraute/Martxueta",
"Mauléon-Licharre/Maule-Lextarre",
"Méharin/Mehaine",
"Mendionde/Lekorne",
"Menditte/Mendikota",
"Mendive/Mendibe",
"Moncayolle-Larrory-Mendibieu/Mitikile-Larrori-Mendibile",
"Montory/Montori",
"Mouguerre/Mugerre",
"Musculdy/Muskildi",
"Ordiarp/Urdiñarbe",
"Orègue/Oragarre",
"Orsanco/Ostankoa",
"Ossas-Suhare/Ozaze-Zühara",
"Osserain-Rivareyte/Ozaraine-Erribareita",
"Ossès/Ortzaize",
"Ostabat-Asme/Izura-Azme",
"Pagolle/Pagola",
"Roquiague/Arrokiaga",
"Sainte-Engrâce/Urdatx",
"Saint-Esteben/Donoztiri",
"Saint-Étienne-De-Baïgorry/Baigorri",
"Saint-Jean-De-Luz/Donibane Lohizune",
"Saint-Jean-Le-Vieux/Donazaharre",
"Saint-Jean-Pied-De-Port/Donibane Garazi",
"Saint-Just-Ibarre/Donaixti-Ibarre",
"Saint-Martin-D'arbéroue/Donamartiri",
"Saint-Martin-D'arrossa/Arrosa",
"Saint-Michel/Eiheralarre",
"Saint-Palais/Donapaleu",
"Saint-Pée-Sur-Nivelle/Senpere",
"Saint-Pierre-D'irube/Hiriburu",
"Sames/Samatze",
"Sare/Sara",
"Sauguis-Saint-Étienne/Zalgize-Doneztebe",
"Souraïde / Zuraide",
"Suhescun/Suhuskune",
"Tardets-Sorholus/Atharratze-Sorholüze",
"Trois-Villes/Iruri",
"Uhart-Cize/Uharte Garazi",
"Uhart-Mixe/Uhartehiri",
"Urcuit/Urketa",
"Urepel/Urepele",
"Urrugne/Urruña",
"Urt/Ahurti",
"Ustaritz/Uztaritze",
"Villefranque/Milafranga",
"Viodos-Abense-De-Bas/Bildoze-Onizepea",
"Alegría-Dulantzi/Dulantzi",
"Amurrio",
"Aramaio",
"Artziniega",
"Armiñón",
"Arrazua-Ubarrundia/Arratzua-Ubarrundia",
"Asparrena",
"Ayala/Aiara/Aiara",
"Baños De Ebro/Mañueta/Mañueta",
"Barrundia",
"Berantevilla",
"Bernedo",
"Campezo/Kanpezu/Kanpezu",
"Zigoitia",
"Kripan",
"Kuartango",
"Elburgo/Burgelu/Burgu",
"Elciego/Eltziego",
"Elvillar / Bilar/Bilar",
"Iruraiz-Gauna/Iruraitz-Gauna",
"Labastida / Bastida/Bastida",
"Lagrán/Lagran",
"Laguardia/Guardia",
"Lanciego/Lantziego/Lantziego",
"Lapuebla De Labarca",
"Leza",
"Laudio / Llodio/Laudio",
"Arraia-Maeztu",
"Moreda De Álava / Moreda Araba/Moreda",
"Navaridas",
"Okondo",
"Oyón-Oion/Oion",
"Peñacerrada-Urizaharra/Urizaharra",
"Erriberagoitia / Ribera Alta/Erriberagoitia",
"Ribera Baja / Erribera Beitia/Erriberabeitia",
"Añana",
"Agurain / Salvatierra/Agurain",
"Samaniego",
"San Millán/Donemiliaga/Donemiliaga",
"Urkabustaiz",
"Valdegovía / Gaubea/Gaubea",
"Harana/Valle De Arana/Harana",
"Villabuena De Álava / Eskuernaga/Villabuena",
"Legutio",
"Vitoria-Gasteiz/Gasteiz",
"Yécora / Iekora/Ekora",
"Zalduondo",
"Zambrana/Zanbrana",
"Zuia",
"Iruña Oka/Iruña De Oca/Iruña Oka",
"Lantarón",
"Condado De Treviño/Trebiñu",
"La Puebla De Arganzón/Argantzun"
];